version: '3.9'

services:
  elasticsearch1:
    image: elasticsearch:8.6.2
    environment:
      - xpack.security.enabled=true
      - discovery.type=zen
      - cluster.name=elasticsearch-cluster
      - node.name=elasticsearch1
      - discovery.seed_hosts=elasticsearch2,elasticsearch3
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTIC_USERNAME=${ELASTIC_USERNAME}
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic-network
  elasticsearch2:
    image: elasticsearch:8.6.2
    environment:
      - xpack.security.enabled=true
      - discovery.type=zen
      - cluster.name=elasticsearch-cluster
      - node.name=elasticsearch2
      - discovery.seed_hosts=elasticsearch1,elasticsearch3
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTIC_USERNAME=${ELASTIC_USERNAME}
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic-network
  elasticsearch3:
    image: elasticsearch:8.6.2
    environment:
      - xpack.security.enabled=true
      - discovery.type=zen
      - cluster.name=elasticsearch-cluster
      - node.name=elasticsearch3
      - discovery.seed_hosts=elasticsearch1,elasticsearch2
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTIC_USERNAME=${ELASTIC_USERNAME}
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic-network

networks:
  elastic-network:
    driver: bridge
